prepare:
	unzip ./stimuli.zip
	wget https://download.pytorch.org/models/densenet169-b2777c0a.pth -O ./densenet/densenet169-b2777c0a.pth
	wget https://download.pytorch.org/models/resnet101-5d3b4d8f.pth -O ./resnet/resnet101-5d3b4d8f.pth
	wget  https://s3.amazonaws.com/cornet-models/cornet_s-1d3f7974.pth -O ./cornet/cornet_s-1d3f7974.pth
